/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author CailynRae
 */
public class Songs extends javax.swing.JPanel {

    /**
     * Creates new form Songs
     */
    public Songs(String songName, String artistName, String i, String dateAdd, URL url) throws IOException {
        initComponents();
        index.setText(i);
        songTitle.setText(songName);
        artist.setText(artistName);
        date.setText(dateAdd);
        
        Image image = ImageIO.read(url);
        ImageIcon playlistImage = new ImageIcon(image);
        int labelWidth = songPic.getWidth();
        Image scaledImage = playlistImage.getImage().getScaledInstance(labelWidth, -1, Image.SCALE_SMOOTH);
            
        ImageIcon playlistPic = new ImageIcon(scaledImage);
        songPic.setIcon(playlistPic);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        index = new javax.swing.JLabel();
        songPic = new javax.swing.JLabel();
        songTitle = new javax.swing.JLabel();
        artist = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setBackground(null);
        setPreferredSize(new java.awt.Dimension(1060, 60));
        setLayout(null);

        index.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        index.setForeground(new java.awt.Color(240, 240, 240));
        index.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        index.setText("#");
        add(index);
        index.setBounds(10, 20, 38, 19);

        songPic.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        songPic.setForeground(new java.awt.Color(184, 184, 184));
        songPic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(songPic);
        songPic.setBounds(80, 10, 40, 40);

        songTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        songTitle.setForeground(new java.awt.Color(240, 240, 240));
        songTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        songTitle.setText("Title");
        add(songTitle);
        songTitle.setBounds(140, 20, 310, 19);

        artist.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        artist.setForeground(new java.awt.Color(240, 240, 240));
        artist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        artist.setText("Artist");
        add(artist);
        artist.setBounds(510, 20, 300, 19);

        date.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(240, 240, 240));
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date.setText("Date Added");
        add(date);
        date.setBounds(790, 20, 190, 19);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artist;
    private javax.swing.JLabel date;
    private javax.swing.JLabel index;
    private javax.swing.JLabel songPic;
    private javax.swing.JLabel songTitle;
    // End of variables declaration//GEN-END:variables
}
